Config = {}

-- If you use -1 for testing the fish is very easy to catch --
Config.Difficulty = -1
Config.ReelSpeed = 0.1125
Config.defaultlang = "pt_lang"

Config.DiscordIntegration = true
Config.DiscordWebHook = "https://discord.com/api/webhooks/987328314819612702/1Ugy-LhPJKh4xjDvp2YM_8KdcDvdfWm98vxIeyy3VWiA5tnRrYpCVa4eKbzzb64qK7Zp"
Config.DiscordBotName= "Vorp Fishing"
Config.DiscordAvatar = ""
Config.Debug = true

Config.Baits = {
	"p_baitBread01x",
	"p_baitCorn01x",
	"p_baitCheese01x",
	"p_baitWorm01x",
	"p_baitCricket01x",
	"p_crawdad01x",
	"p_finishedragonfly01x",
	"p_FinisdFishlure01x",
	"p_finishdcrawd01x",
	"p_finishedragonflylegendary01x",
	"p_finisdfishlurelegendary01x",
    "p_finishdcrawdlegendary01x",
    "p_lgoc_spinner_v4",
    "p_lgoc_spinner_v6",
}


Config.BaitsPerFish = {
    ["p_baitBread01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
	    "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
		"A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
    },
    ["p_baitCorn01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
	    "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
		"A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
    },
    ["p_baitCheese01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
	    "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
		"A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
    },
    ["p_baitCricket01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHMUSKIE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHRAINBOWTROUT_01_LG",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
    },
	["p_baitWorm01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHRAINBOWTROUT_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHROCKBASS_01_MS",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_crawdad01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHMUSKIE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
    },
    ["p_finishedragonfly01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_FinisdFishlure01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_finishdcrawd01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_finishedragonflylegendary01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHCHANNELCATFISH_01_LG",
        "A_C_FISHCHANNELCATFISH_01_XL",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_finisdfishlurelegendary01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHANNELCATFISH_01_LG",
        "A_C_FISHCHANNELCATFISH_01_XL",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_finishdcrawdlegendary01x"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHANNELCATFISH_01_LG",
        "A_C_FISHCHANNELCATFISH_01_XL",
        "A_C_FISHLAKESTURGEON_01_LG",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_lgoc_spinner_v4"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHLARGEMOUTHBASS_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHROCKBASS_01_MS",
        "A_C_FISHROCKBASS_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    },
    ["p_lgoc_spinner_v6"] = {
        "A_C_FISHBLUEGIL_01_MS",
        "A_C_FISHBLUEGIL_01_SM",
        "A_C_FISHBULLHEADCAT_01_MS",
        "A_C_FISHBULLHEADCAT_01_SM",
        "A_C_FISHCHAINPICKEREL_01_MS",
        "A_C_FISHCHAINPICKEREL_01_SM",
        "A_C_FISHLARGEMOUTHBASS_01_LG",
        "A_C_FISHLARGEMOUTHBASS_01_MS",
        "A_C_FISHLONGNOSEGAR_01_LG",
        "A_C_FISHNORTHERNPIKE_01_LG",
        "A_C_FISHPERCH_01_MS",
        "A_C_FISHPERCH_01_SM",
        "A_C_FISHREDFINPICKEREL_01_MS",
        "A_C_FISHREDFINPICKEREL_01_SM",
        "A_C_FISHROCKBASS_01_MS",
        "A_C_FISHROCKBASS_01_SM",
        "A_C_FISHSALMONSOCKEYE_01_LG",
        "A_C_FISHSALMONSOCKEYE_01_ML",
        "A_C_FISHSALMONSOCKEYE_01_MS",
        "A_C_FISHSMALLMOUTHBASS_01_LG",
        "A_C_FISHSMALLMOUTHBASS_01_MS",
    }
}

Config.Lang = {

	ReadyToFish = "Pronto para pescar!",
    PrepRod = "Preparar vara de pesca",
    ThrowHook = "Jogar Linha",
    --------------------------------
	Fishing = "Pescando",
	HookFish = "Fisgar",
    ReelLure = "Enrolar Linha",
    --------------------------------
	MiniGame = "Pegue o peixe!",
	ReelIn = "Enrolar",
	Cancel = "Cancelar",
	--------------------------------
    FishName = "Nome",
    FishWeight = "Peso",
    KeepFish = "Continuar Pescando",
    ThrowFish = "Soltar o peixe",
    --------------------------------
    discord_fishCaught = "pegou um peixe!",
    discord_fishKept = "O peixe foi mantido!  😁",
    discord_fishThrow = "O peixe foi jogado fora! 😭",
    discord_fieldFishName = "🦈 Nome do peixe: ",
    discord_fieldFishWeight = "⚖ Peso: "
}




Config.fishData = {
	A_C_FISHBLUEGIL_01_MS        = {"Blue Gil (Medio)","PROVISION_FISH_BLUEGILL","PROVISION_BLUEGILL_DESC"},
	A_C_FISHBLUEGIL_01_SM        = {"Blue Gil (Pequeno)","PROVISION_FISH_BLUEGILL","PROVISION_BLUEGILL_DESC"},
	A_C_FISHBULLHEADCAT_01_MS    = {"Bagre (Médio)","PROVISION_FISH_BULLHEAD_CATFISH","PROVISION_BLUEGILL_DESC"},
	A_C_FISHBULLHEADCAT_01_SM    = {"Bagre (Pequeno)","PROVISION_FISH_BULLHEAD_CATFISH","PROVISION_BLUEGILL_DESC"},
	A_C_FISHCHAINPICKEREL_01_MS  = {"Luccio (Médio)","PROVISION_FISH_CHAIN_PICKEREL","PROVISION_CHNPKRL_DESC"},
	A_C_FISHCHAINPICKEREL_01_SM  = {"Luccio (Pequeno)","PROVISION_FISH_CHAIN_PICKEREL","PROVISION_CHNPKRL_DESC"},
	A_C_FISHCHANNELCATFISH_01_LG = {"Peixe-gato do canal (grande)","PROVISION_FISH_CHANNEL_CATFISH","PROVISION_CHNCATFSH_DESC"},
	A_C_FISHCHANNELCATFISH_01_XL = {"Peixe-gato do canal (Extra grande)","PROVISION_FISH_CHANNEL_CATFISH","PROVISION_CHNCATFSH_DESC"},
	A_C_FISHLAKESTURGEON_01_LG   = {"Esturjão do Lago (grande)","PROVISION_FISH_LAKE_STURGEON","PROVISION_LKSTURG_DESC"},
	A_C_FISHLARGEMOUTHBASS_01_LG = {"Robalo Grande (Grande)","PROVISION_FISH_LARGEMOUTH_BASS","PROVISION_LRGMTHBASS_DESC"},
	A_C_FISHLARGEMOUTHBASS_01_MS = {"Robalo Grande (Médio)","PROVISION_FISH_LARGEMOUTH_BASS","PROVISION_LRGMTHBASS_DESC"},
	A_C_FISHLONGNOSEGAR_01_LG    = {"Peixe de Nariz longo (Grande)","PROVISION_FISH_LONGNOSE_GAR","PROVISION_LNGNOSEGAR_DESC"},
	A_C_FISHMUSKIE_01_LG         = {"Almíscar (grande)","PROVISION_FISH_MUSKIE","PROVISION_MUSKIE_DESC"},
	A_C_FISHNORTHERNPIKE_01_LG   = {"Lúcio do Norte (Grande)","PROVISION_FISH_NORTHERN_PIKE","PROVISION_NPIKE_DESC"},
	A_C_FISHPERCH_01_MS          = {"Peixe Poleiro (médio)","PROVISION_FISH_PERCH","PROVISION_PERCH_DESC"},
	A_C_FISHPERCH_01_SM          = {"Peixe Poleiro (pequeno)","PROVISION_FISH_PERCH","PROVISION_PERCH_DESC"},
	A_C_FISHRAINBOWTROUT_01_LG   = {"Truta Arco-íris (Grande)","PROVISION_FISH_STEELHEAD_TROUT","PROVISION_FISH_STHDTROUT_DESC"},
	A_C_FISHRAINBOWTROUT_01_MS   = {"Truta Arco-íris (Médio)","PROVISION_FISH_STEELHEAD_TROUT","PROVISION_FISH_STHDTROUT_DESC"},
	A_C_FISHREDFINPICKEREL_01_MS = {"Luccio vermelhol (Médio)","PROVISION_FISH_REDFIN_PICKEREL","PROVISION_RDFNPCKREL_DESC"},
	A_C_FISHREDFINPICKEREL_01_SM = {"Luccio vermelho (pequeno)","PROVISION_FISH_REDFIN_PICKEREL","PROVISION_RDFNPCKREL_DESC"},
	A_C_FISHROCKBASS_01_MS       = {"Robalo (Medio)","PROVISION_FISH_ROCK_BASS","PROVISION_ROCKBASS_DESC"},
	A_C_FISHROCKBASS_01_SM       = {"Robalo (Pequeno)","PROVISION_FISH_ROCK_BASS","PROVISION_ROCKBASS_DESC"},
	A_C_FISHSALMONSOCKEYE_01_LG  = {"Salmão Vermelho (Grande)","PROVISION_FISH_SOCKEYE_SALMON_LEGENDARY","PROVISION_SCKEYESAL_DESC"},
	A_C_FISHSALMONSOCKEYE_01_ML  = {"Salmão Vermelho (Médio-Grande)","PROVISION_FISH_SOCKEYE_SALMON","PROVISION_SCKEYESAL_DESC"},
	A_C_FISHSALMONSOCKEYE_01_MS  = {"Salmão vermelho (Medio)","PROVISION_FISH_SOCKEYE_SALMON","PROVISION_SCKEYESAL_DESC"},
	A_C_FISHSMALLMOUTHBASS_01_LG = {"Robalo Pequeno (Grande)","PROVISION_FISH_SMALLMOUTH_BASS","PROVISION_SMLMTHBASS_DESC"},
	A_C_FISHSMALLMOUTHBASS_01_MS = {"Robalo Pequeno (Medio)","PROVISION_FISH_SMALLMOUTH_BASS","PROVISION_SMLMTHBASS_DESC"},
}


