Config2 = {}
Config2.Language = {
    ["presstobuy"] = "Personalizar armas",
    ["presstocraft"] = " Criar armas",
    ["presstoshop"] = "Armas",
    ["tooclose"] = "Alguém está muito perto",
    ["openmenu"] = "Abrir",
    ["rotateitem1"] = "Press ~e~1~q~ Para girar a arma",
    ["rotateitem2"] = "Press ~e~2~q~ Para girar a arma",
    ["rotateitem3"] = "Press ~e~3~q~ Para girar a arma",
    ["rotateitem4"] = "Press ~e~4~q~ Para girar a arma",

    ["dollar"] = " $",



    ["craftingloading"] = "Criando...",
    ["customloading"] = "Criando Cuztomizações..",
    ["pleaserequip"] = "Re-equipe sua arma pelo inventario",
    ["scrolltoexit"] = "Role até o fundo para sair do menu",
    ["wrongjobcuztom"] = "Você não tem o trabalho necessário para usar a cuztomização",
    ["wrongjobcrafting"] = "Você não tem o trabalho necessário para usar a criação",
    ["customization"] = "Modificar armas",
    ["crafting"] = "Criação",
    ["shop"] = "Loja de Armas",
    ["buyweapons"] = "Comprar Armas",
    ["buyammo"] = "Comprar Munição",
    ["weaponcrafting"] = "Criação de Arma",
    ["ammocrafting"] = "Criação de Munições",
    ["areusureexit"] = "Você tem certeza que deseja sair ?",
    ["comps"] = "Componentes de armas",
    ["sights"] = "Mira de armas",
    ["rifling"] = "Aprimoramento de arma",
    ["other"] = "Cano de Arma",
    ["scopecolor"] = "Material do Escope",
    ["wrap"] = "Envolto da arma",
    ["wrapcolor"] = "Cor do envoltório",
    ["barrel"] = "Material do Cano da Arma",
    ["trigger"] = "Material do gatilho",
    ["variant"] = "Variante de arma",
    ["frame"] = "Material do Corpo da Arma",
    ["frontsight"] = "Material de mira",
    ["cylinder"] = "Material do mecanismo",
    ["gripbody"] = "Material do Grip",
    ["grip"] = "Grip",
    ["decal"] = "Decalques de armas",
    ["decalcylinder"] = "Decalques do Mecanismo",
    ["decalframe"] = "Decalques do Corpo da Arma",
    ["decalbarrel"] = "Decalques do Cano da Arma",
    ["decalcolor"] = "Materiais de decalques",
    ["cylinder2"] = "Material de decalques do mecanismo",
    ["frame2"] = "Material dos Decalques do Corpo da Arma",
    ["barrel2"] = "Material de Decalques do Cano da Arma",
    ["buyselect"] = "Comprar Selecionados",
    ["total"] = "Total: ",
    ["exitmenu"] = "Sair do Menu",
    ["cost"] = "Custo: ",
    ["craft"] = "Criar",
    ["count"] = "Qtd: ",
    ["yes"] = "Sim",
    ["no"] = "Não",
    ["remove"] = "Remover",
    ["price"] = " / Preço: ",
    ["label"] = "Nome: ",
    ["wrongwptype"] = "Tipo de arma errada",
    ["craftingwepmods"] = "Criação de mods de arma",
    ["cantafford"] = "Não posso pagar",
    ["syn_weapons"] = "Armas: ",
    ["bought"] = " Comprou ",
    ["youboughta"] = "Você comprou um ",
    ["fors"] = " Por ",
    ["nomoney"] = "Você não tem dinheiro suficiente",
    ["cantcarrywep"] = "Não posso carregar mais armas",
    ["cantcarryitem"] = "Não posso carregar mais itens",
    ["crafted"] = " Criada ",
    ["nomaterial"] = "Não há materiais suficientes",
    ["weprec"] = "Você recebeu uma arma",




    ----- new lines
    ["confirm"] = "Confirm",
    ["amount"] = "Amount",
    ["invalidamount"] = "Invalid Amount",
}
