-- Smoke Weed // Fumer du Weed
RegisterNetEvent("col_drugs:weed")
AddEventHandler("col_drugs:weed", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_SMOKE_INTERACTION'), 20000, true, false, false, false)
    Wait(20000)
	AnimpostfxPlay("PlayerDrugsPoisonWell")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	Wait(60000) -- 1 min effect/duration
	AnimpostfxStop("PlayerDrugsPoisonWell")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)


-- Magic Mush to Eat // Manger des Champignons Magic
RegisterNetEvent("col_drugs:oppio")
AddEventHandler("col_drugs:oppio", function()
	Manger()
	AnimpostfxPlay("PlayerDrunkAberdeen")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	TriggerEvent('DevDokus:Metabolism:C:Stamina', 30)
	Wait(60000) -- 1 min effect/duration
	AnimpostfxStop("PlayerDrunkAberdeen")
	TriggerEvent('stress:modify',  -75.5)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -15)
	TriggerEvent('DevDokus:Metabolism:C:Hunger', -15)
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)


-- BEBAIDAS ALCOLICAS
RegisterNetEvent("col_drugs:moonshine")
AddEventHandler("col_drugs:moonshine", function(stress)
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -7)
	TriggerEvent('DevDokus:Metabolism:C:Hunger', -7)
	Wait(60000) -- 1 min effect/duration
	TriggerEvent('stress:modify',  stress)
	AnimpostfxStop("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:vodka")
AddEventHandler("col_drugs:vodka", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -7)
	TriggerEvent('DevDokus:Metabolism:C:Hunger', -7)
	Wait(60000) -- 1 min effect/duration
	AnimpostfxStop("PlayerDrunk01")
	TriggerEvent('stress:modify',  -10.5)
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:rum")
AddEventHandler("col_drugs:rum", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -7)
	TriggerEvent('DevDokus:Metabolism:C:Hunger', -7)
	Wait(60000) -- 1 min effect/duration
	AnimpostfxStop("PlayerDrunk01")
	TriggerEvent('stress:modify',  -10.5)
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:whisky")
AddEventHandler("col_drugs:whisky", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -7)
	TriggerEvent('DevDokus:Metabolism:C:Hunger', -7)
	Wait(60000) -- 1 min effect/duration
	AnimpostfxStop("PlayerDrunk01")
	TriggerEvent('stress:modify',  -10.5)
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:cerveja")
AddEventHandler("col_drugs:cerveja", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -7)
	TriggerEvent('DevDokus:Metabolism:C:Hunger', -7)
	Wait(60000) -- 1 min effect/duration
	AnimpostfxStop("PlayerDrunk01")
	TriggerEvent('stress:modify',  -10.5)
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:cidra")
AddEventHandler("col_drugs:cidra", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -7)
	TriggerEvent('DevDokus:Metabolism:C:Hunger', -7)
	Wait(60000) -- 1 min effect/duration
	AnimpostfxStop("PlayerDrunk01")
	TriggerEvent('stress:modify',  -10.5)
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:daiquiri")
AddEventHandler("col_drugs:daiquiri", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	Wait(80000) -- 1 min 20 effect/duration
	TriggerEvent('stress:modify',  -20.5)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -5)
	AnimpostfxStop("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:oldfashioned")
AddEventHandler("col_drugs:oldfashioned", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	Wait(80000) -- 1 min 20 effect/duration
	TriggerEvent('stress:modify',  -20.5)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -5)
	AnimpostfxStop("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:planterspunch")
AddEventHandler("col_drugs:planterspunch", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	Wait(80000) -- 1 min 20 effect/duration
	TriggerEvent('stress:modify',  -20.5)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -5)
	AnimpostfxStop("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:vodkamartini")
AddEventHandler("col_drugs:vodkamartini", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	Wait(80000) -- 1 min 20 effect/duration
	TriggerEvent('stress:modify',  -20.5)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -5)
	AnimpostfxStop("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)
RegisterNetEvent("col_drugs:mojito")
AddEventHandler("col_drugs:mojito", function()
    local playerPed = PlayerPedId()
    TaskStartScenarioInPlace(playerPed, GetHashKey('WORLD_HUMAN_DRINKING'), 20000, true, false, false, false)
    Wait(20000)
	ClearPedTasksImmediately(PlayerPedId())
	AnimpostfxPlay("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.95)
	Wait(80000) -- 1 min 20 effect/duration
	TriggerEvent('stress:modify',  -20.5)
	TriggerEvent('DevDokus:Metabolism:C:Thirst', -5)
	AnimpostfxStop("PlayerDrunk01")
	Citizen.InvokeNative(0x406CCF555B04FAD3 , PlayerPedId(), 1, 0.00)
end)



function Manger()
    Eat = true
    local ped = PlayerPedId()

    local playerPed = PlayerPedId()
    local prop_name = 's_amedmush'
    local x,y,z = table.unpack(GetEntityCoords(playerPed))
    local prop = CreateObject(GetHashKey(prop_name), x, y, z + 0.2, true, true, true)
    local boneIndex = GetEntityBoneIndexByName(playerPed, "SKEL_R_Finger00")

    RequestAnimDict("amb_misc@world_human_eat_apple@male_a@wip_base")
    while not HasAnimDictLoaded("amb_misc@world_human_eat_apple@male_a@wip_base") do
        Citizen.Wait(100)
    end
    if  IsPedMale(playerPed) then
        TaskPlayAnim(playerPed, "amb_misc@world_human_eat_apple@male_a@wip_base", "wip_base", 8.0, -8.0, 5500, 0, 0, true, 0, false, 0, false)
        AttachEntityToEntity(prop, playerPed,boneIndex, 0.00, 0.0, 0.0, 1.024, 70.0, 100.0, true, true, false, true, 1, true)
        Wait(5500)
        ClearPedSecondaryTask(playerPed)
        DeleteObject(prop)
    else
        TaskPlayAnim(playerPed, "amb_misc@world_human_eat_apple@male_a@wip_base", "wip_base", 8.0, -8.0, 5500, 0, 0, true, 0, false, 0, false)
        AttachEntityToEntity(prop, playerPed,boneIndex, 0.00, 0.0, 0.0, 1.024, 70.0, 100.0, true, true, false, true, 1, true)
        Wait(5500)
        ClearPedSecondaryTask(playerPed)
        DeleteObject(prop)
    end
    Eat = false
end