VORP = exports.vorp_inventory:vorp_inventoryApi()

-- Weed/Smoke/Fumer
VORP.RegisterUsableItem("weed", function(data)
	VORP.subItem(data.source, "weed", 1)
	TriggerClientEvent('col_drugs:weed', data.source)
end)

-- Moonshine/Drink/Drunk/Alcool
VORP.RegisterUsableItem("moonshine", function(data)
	VORP.subItem(data.source, "moonshine", 1)
	local stress = -50
	TriggerClientEvent('col_drugs:moonshine', data.source, stress)
end)
VORP.RegisterUsableItem("appleCrumbMoonshine", function(data)
	VORP.subItem(data.source, "appleCrumbMoonshine", 1)
	TriggerClientEvent('col_drugs:moonshine', data.source)
end)
VORP.RegisterUsableItem("wildCiderMoonshine", function(data)
	VORP.subItem(data.source, "wildCiderMoonshine", 1)
	TriggerClientEvent('col_drugs:moonshine', data.source)
end)
VORP.RegisterUsableItem("tropicalPunchMoonshine", function(data)
	VORP.subItem(data.source, "tropicalPunchMoonshine", 1)
	local stress = -55
	TriggerClientEvent('col_drugs:moonshine', data.source, stress)
end)
VORP.RegisterUsableItem("vodka", function(data)
	VORP.subItem(data.source, "vodka", 1)
	TriggerClientEvent('col_drugs:vodka', data.source)
end)
VORP.RegisterUsableItem("rum", function(data)
	VORP.subItem(data.source, "rum", 1)
	TriggerClientEvent('col_drugs:rum', data.source)
end)
VORP.RegisterUsableItem("whisky", function(data)
	VORP.subItem(data.source, "whisky", 1)
	TriggerClientEvent('col_drugs:whisky', data.source)
end)
VORP.RegisterUsableItem("cerveja", function(data)
	VORP.subItem(data.source, "cerveja", 1)
	TriggerClientEvent('col_drugs:cerveja', data.source)
end)
VORP.RegisterUsableItem("cidra", function(data)
	VORP.subItem(data.source, "cidra", 1)
	TriggerClientEvent('col_drugs:cidra', data.source)
end)
VORP.RegisterUsableItem("daiquiri", function(data)
	VORP.subItem(data.source, "daiquiri", 1)
	TriggerClientEvent('col_drugs:daiquiri', data.source)
end)
VORP.RegisterUsableItem("oldfashioned", function(data)
	VORP.subItem(data.source, "oldfashioned", 1)
	TriggerClientEvent('col_drugs:oldfashioned', data.source)
end)
VORP.RegisterUsableItem("planterspunch", function(data)
	VORP.subItem(data.source, "planterspunch", 1)
	TriggerClientEvent('col_drugs:planterspunch', data.source)
end)
VORP.RegisterUsableItem("vodkamartini", function(data)
	VORP.subItem(data.source, "vodkamartini", 1)
	TriggerClientEvent('col_drugs:vodkamartini', data.source)
end)
VORP.RegisterUsableItem("mojito", function(data)
	VORP.subItem(data.source, "mojito", 1)
	TriggerClientEvent('col_drugs:mojito', data.source)
end)

-- Oppio/Eat/Manger
VORP.RegisterUsableItem("oppio", function(data)
	VORP.subItem(data.source, "oppio", 1)
	TriggerClientEvent('col_drugs:oppio', data.source)
end)